### ISSUE TITLE
libndt: make Client methods private, unless needed by users

### ISSUE THREAD

**Issue by pboothe** [measurement-kit/libndt#17]
Use friend classes to enable unit tests.

**Comment by bassosimone** [comment]
Make `protected` the methods that one _may_ want to override for specific use cases (e.g. MK)

**Comment by bassosimone** [comment]
Not super practical to make stuff really _private_ because we directly call what would become private methods from unnamed functions in the unit tests. For now, the solution I've adopted is to document all that needed to be public, clearly specified in the header that, below a certain line, everything is considered to be internal. I think this is good enough. See #26.

**Comment by bassosimone** [comment]
Going to close this issue, as we concluded with @pboothe that the implementation is good enough.
